spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

#spring.batch.jdbc.initialize-schema = always
server:
  port: 9091
